export function getPresetData() {
  return {
    bass: [
      {
        name: "Deep Sub Bass",
        osc1: { wave: "sine", detune: 0, level: 100 },
        osc2: { wave: "sine", detune: -12, level: 50 },
        noiseLevel: 0,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 200,
          resonance: 1,
          envAmount: 0,
          attack: 0.01,
          decay: 0.1,
        },
        ampEnv: { attack: 0.01, decay: 0.3, sustain: 0.7, release: 0.5 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 30,
          delayMix: 0,
          reverbMix: 10,
        },
        masterVolume: 60,
      },
      {
        name: "Funky Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 7, level: 40 },
        noiseLevel: 5,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 800,
          resonance: 8,
          envAmount: 1200,
          attack: 0.01,
          decay: 0.15,
        },
        ampEnv: { attack: 0.01, decay: 0.2, sustain: 0.3, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 6,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 20,
          delayMix: 0,
          reverbMix: 5,
        },
        masterVolume: 55,
      },
      {
        name: "Acid Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 0, level: 70 },
        noiseLevel: 0,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 400,
          resonance: 20,
          envAmount: 3000,
          attack: 0.01,
          decay: 0.4,
        },
        ampEnv: { attack: 0.01, decay: 0.3, sustain: 0.5, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 8,
          pitchDepth: 0,
          filterDepth: 1500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 25,
          delayMix: 15,
          reverbMix: 20,
        },
        masterVolume: 50,
      },
      {
        name: "Wobble Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: -7, level: 80 },
        noiseLevel: 0,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 1500,
          resonance: 10,
          envAmount: 0,
          attack: 0.01,
          decay: 0.1,
        },
        ampEnv: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.3 },
        lfo: {
          wave: "square",
          rate: 4,
          pitchDepth: 0,
          filterDepth: 2500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 30,
          delayMix: 0,
          reverbMix: 15,
        },
        masterVolume: 50,
      },
      {
        name: "Punch Bass",
        osc1: { wave: "triangle", detune: 0, level: 100 },
        osc2: { wave: "sine", detune: -12, level: 60 },
        noiseLevel: 10,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 600,
          resonance: 3,
          envAmount: 800,
          attack: 0.001,
          decay: 0.1,
        },
        ampEnv: { attack: 0.001, decay: 0.15, sustain: 0.6, release: 0.25 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 20,
          delayMix: 0,
          reverbMix: 5,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 60,
      },
      {
        name: "Reese Bass",
        osc1: { wave: "sawtooth", detune: -7, level: 100 },
        osc2: { wave: "sawtooth", detune: 7, level: 100 },
        noiseLevel: 0,
        octave: 2,
        filter: {
          type: "lowpass",
          cutoff: 350,
          resonance: 4,
          envAmount: 200,
          attack: 0.02,
          decay: 0.2,
        },
        ampEnv: { attack: 0.02, decay: 0.3, sustain: 0.9, release: 0.4 },
        lfo: {
          wave: "sine",
          rate: 0.2,
          pitchDepth: 3,
          filterDepth: 100,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 25,
          delayMix: 0,
          reverbMix: 20,
          distortionDrive: 15,
          chorusRate: 0.3,
          chorusDepth: 30,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 55,
      },
      {
        name: "Electro Bass",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: -12, level: 60 },
        noiseLevel: 3,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 500,
          resonance: 12,
          envAmount: 1500,
          attack: 0.001,
          decay: 0.08,
        },
        ampEnv: { attack: 0.001, decay: 0.1, sustain: 0.2, release: 0.15 },
        lfo: {
          wave: "sine",
          rate: 12,
          pitchDepth: 0,
          filterDepth: 800,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.25,
          delayFeedback: 30,
          delayMix: 10,
          reverbMix: 15,
          distortionDrive: 20,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 55,
      },
      {
        name: "Growl Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: -5, level: 90 },
        noiseLevel: 8,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 600,
          resonance: 18,
          envAmount: 2500,
          attack: 0.02,
          decay: 0.25,
        },
        ampEnv: { attack: 0.01, decay: 0.2, sustain: 0.7, release: 0.3 },
        lfo: {
          wave: "square",
          rate: 6,
          pitchDepth: 10,
          filterDepth: 2000,
          ampDepth: 15,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 35,
          delayMix: 5,
          reverbMix: 10,
          distortionDrive: 35,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 50,
      },
      {
        name: "Slap Bass",
        osc1: { wave: "triangle", detune: 0, level: 100 },
        osc2: { wave: "sine", detune: 0, level: 40 },
        noiseLevel: 20,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 1200,
          resonance: 5,
          envAmount: 2000,
          attack: 0.001,
          decay: 0.06,
        },
        ampEnv: { attack: 0.001, decay: 0.08, sustain: 0.4, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 20,
          delayMix: 0,
          reverbMix: 5,
          distortionDrive: 10,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 58,
      },
      {
        name: "TB-303 Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 0, level: 50 },
        noiseLevel: 0,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 300,
          resonance: 22,
          envAmount: 3500,
          attack: 0.001,
          decay: 0.5,
        },
        ampEnv: { attack: 0.001, decay: 0.4, sustain: 0.4, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 30,
          delayMix: 15,
          reverbMix: 25,
          distortionDrive: 8,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 52,
      },
      {
        name: "Deep House Bass",
        osc1: { wave: "sine", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 0, level: 50 },
        noiseLevel: 0,
        octave: 2,
        filter: {
          type: "lowpass",
          cutoff: 180,
          resonance: 2,
          envAmount: 100,
          attack: 0.05,
          decay: 0.3,
        },
        ampEnv: { attack: 0.05, decay: 0.4, sustain: 0.7, release: 0.6 },
        lfo: {
          wave: "sine",
          rate: 0.5,
          pitchDepth: 0,
          filterDepth: 50,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.5,
          delayFeedback: 35,
          delayMix: 10,
          reverbMix: 30,
          distortionDrive: 5,
          chorusRate: 0.4,
          chorusDepth: 20,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 60,
      },
      {
        name: "Techno Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 0, level: 70 },
        noiseLevel: 5,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 700,
          resonance: 8,
          envAmount: 1000,
          attack: 0.001,
          decay: 0.12,
        },
        ampEnv: { attack: 0.001, decay: 0.15, sustain: 0.5, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 4,
          pitchDepth: 0,
          filterDepth: 600,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.375,
          delayFeedback: 40,
          delayMix: 20,
          reverbMix: 15,
          distortionDrive: 25,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 53,
      },
      {
        name: "Dubstep Bass",
        osc1: { wave: "sawtooth", detune: -5, level: 100 },
        osc2: { wave: "square", detune: 5, level: 100 },
        noiseLevel: 10,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 800,
          resonance: 15,
          envAmount: 0,
          attack: 0.01,
          decay: 0.1,
        },
        ampEnv: { attack: 0.01, decay: 0.1, sustain: 0.95, release: 0.3 },
        lfo: {
          wave: "square",
          rate: 3,
          pitchDepth: 0,
          filterDepth: 3000,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 50,
          delayMix: 15,
          reverbMix: 30,
          distortionDrive: 45,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Smooth Bass",
        osc1: { wave: "triangle", detune: 0, level: 100 },
        osc2: { wave: "sine", detune: -12, level: 80 },
        noiseLevel: 0,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 400,
          resonance: 1.5,
          envAmount: 300,
          attack: 0.08,
          decay: 0.2,
        },
        ampEnv: { attack: 0.08, decay: 0.25, sustain: 0.8, release: 0.5 },
        lfo: {
          wave: "sine",
          rate: 3,
          pitchDepth: 5,
          filterDepth: 150,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 25,
          delayMix: 5,
          reverbMix: 25,
          distortionDrive: 0,
          chorusRate: 0.6,
          chorusDepth: 35,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 55,
      },
      {
        name: "Distorted Sub",
        osc1: { wave: "sine", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 0, level: 60 },
        noiseLevel: 5,
        octave: 2,
        filter: {
          type: "lowpass",
          cutoff: 250,
          resonance: 3,
          envAmount: 0,
          attack: 0.01,
          decay: 0.1,
        },
        ampEnv: { attack: 0.01, decay: 0.2, sustain: 0.9, release: 0.4 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 25,
          delayMix: 0,
          reverbMix: 10,
          distortionDrive: 40,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 58,
      },
      {
        name: "Rubber Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 12, level: 70 },
        noiseLevel: 0,
        octave: 3,
        filter: {
          type: "bandpass",
          cutoff: 600,
          resonance: 10,
          envAmount: 1800,
          attack: 0.01,
          decay: 0.3,
        },
        ampEnv: { attack: 0.01, decay: 0.25, sustain: 0.6, release: 0.3 },
        lfo: {
          wave: "triangle",
          rate: 8,
          pitchDepth: 20,
          filterDepth: 1200,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 30,
          delayMix: 10,
          reverbMix: 20,
          distortionDrive: 15,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 52,
      },
      {
        name: "Filtered Bass",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 5, level: 80 },
        noiseLevel: 3,
        octave: 3,
        filter: {
          type: "highpass",
          cutoff: 150,
          resonance: 8,
          envAmount: 800,
          attack: 0.02,
          decay: 0.2,
        },
        ampEnv: { attack: 0.02, decay: 0.2, sustain: 0.7, release: 0.35 },
        lfo: {
          wave: "sine",
          rate: 6,
          pitchDepth: 0,
          filterDepth: 500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 35,
          delayMix: 15,
          reverbMix: 25,
          distortionDrive: 18,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 54,
      },
      {
        name: "Vintage Bass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: -3, level: 60 },
        noiseLevel: 8,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 550,
          resonance: 6,
          envAmount: 900,
          attack: 0.01,
          decay: 0.18,
        },
        ampEnv: { attack: 0.01, decay: 0.2, sustain: 0.65, release: 0.3 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.35,
          delayFeedback: 28,
          delayMix: 8,
          reverbMix: 18,
          distortionDrive: 12,
          chorusRate: 0.7,
          chorusDepth: 25,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 56,
      },
      {
        name: "Massive Bass",
        osc1: { wave: "sawtooth", detune: -10, level: 100 },
        osc2: { wave: "sawtooth", detune: 10, level: 100 },
        noiseLevel: 5,
        octave: 2,
        filter: {
          type: "lowpass",
          cutoff: 400,
          resonance: 5,
          envAmount: 600,
          attack: 0.03,
          decay: 0.3,
        },
        ampEnv: { attack: 0.03, decay: 0.35, sustain: 0.85, release: 0.5 },
        lfo: {
          wave: "sine",
          rate: 0.4,
          pitchDepth: 8,
          filterDepth: 200,
          ampDepth: 5,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 30,
          delayMix: 12,
          reverbMix: 35,
          distortionDrive: 20,
          chorusRate: 0.3,
          chorusDepth: 40,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 52,
      },
    ],
    lead: [
      {
        name: "Classic Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 7, level: 70 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3000,
          resonance: 5,
          envAmount: 2000,
          attack: 0.05,
          decay: 0.3,
        },
        ampEnv: { attack: 0.01, decay: 0.2, sustain: 0.7, release: 0.4 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 20,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.375,
          delayFeedback: 35,
          delayMix: 25,
          reverbMix: 30,
        },
        masterVolume: 50,
      },
      {
        name: "Square Lead",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "square", detune: -5, level: 80 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 2500,
          resonance: 3,
          envAmount: 1500,
          attack: 0.08,
          decay: 0.25,
        },
        ampEnv: { attack: 0.02, decay: 0.15, sustain: 0.8, release: 0.3 },
        lfo: {
          wave: "sine",
          rate: 6,
          pitchDepth: 15,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.25,
          delayFeedback: 40,
          delayMix: 20,
          reverbMix: 25,
        },
        masterVolume: 50,
      },
      {
        name: "Synth Brass",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: -7, level: 90 },
        noiseLevel: 5,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 2000,
          resonance: 6,
          envAmount: 1000,
          attack: 0.2,
          decay: 0.3,
        },
        ampEnv: { attack: 0.15, decay: 0.2, sustain: 0.8, release: 0.5 },
        lfo: {
          wave: "sine",
          rate: 4,
          pitchDepth: 10,
          filterDepth: 300,
          ampDepth: 5,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 25,
          delayMix: 15,
          reverbMix: 35,
        },
        masterVolume: 55,
      },
      {
        name: "Pluck Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 12, level: 50 },
        noiseLevel: 8,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 4000,
          resonance: 2,
          envAmount: 3000,
          attack: 0.001,
          decay: 0.15,
        },
        ampEnv: { attack: 0.001, decay: 0.2, sustain: 0.3, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.5,
          delayFeedback: 45,
          delayMix: 35,
          reverbMix: 40,
        },
        masterVolume: 55,
      },
      {
        name: "Distorted Lead",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 14, level: 100 },
        noiseLevel: 3,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3500,
          resonance: 15,
          envAmount: 2500,
          attack: 0.02,
          decay: 0.2,
        },
        ampEnv: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.3 },
        lfo: {
          wave: "sine",
          rate: 7,
          pitchDepth: 25,
          filterDepth: 500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 50,
          delayMix: 30,
          reverbMix: 25,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 45,
      },
      {
        name: "Supersaw Lead",
        osc1: { wave: "sawtooth", detune: -12, level: 90 },
        osc2: { wave: "sawtooth", detune: 12, level: 90 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3500,
          resonance: 4,
          envAmount: 1800,
          attack: 0.06,
          decay: 0.25,
        },
        ampEnv: { attack: 0.02, decay: 0.2, sustain: 0.75, release: 0.4 },
        lfo: {
          wave: "sine",
          rate: 5.5,
          pitchDepth: 18,
          filterDepth: 400,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 38,
          delayMix: 28,
          reverbMix: 35,
          distortionDrive: 0,
          chorusRate: 0.8,
          chorusDepth: 45,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Trance Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 7, level: 70 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 4000,
          resonance: 8,
          envAmount: 2500,
          attack: 0.03,
          decay: 0.25,
        },
        ampEnv: { attack: 0.01, decay: 0.15, sustain: 0.8, release: 0.35 },
        lfo: {
          wave: "sine",
          rate: 6,
          pitchDepth: 22,
          filterDepth: 600,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.375,
          delayFeedback: 42,
          delayMix: 30,
          reverbMix: 40,
          distortionDrive: 8,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 50,
      },
      {
        name: "Screamer Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 5, level: 90 },
        noiseLevel: 5,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 5000,
          resonance: 18,
          envAmount: 3000,
          attack: 0.02,
          decay: 0.2,
        },
        ampEnv: { attack: 0.005, decay: 0.1, sustain: 0.9, release: 0.25 },
        lfo: {
          wave: "sine",
          rate: 7.5,
          pitchDepth: 30,
          filterDepth: 800,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 45,
          delayMix: 25,
          reverbMix: 30,
          distortionDrive: 35,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 47,
      },
      {
        name: "Soft Lead",
        osc1: { wave: "triangle", detune: 0, level: 100 },
        osc2: { wave: "sine", detune: 12, level: 60 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 2000,
          resonance: 2,
          envAmount: 800,
          attack: 0.12,
          decay: 0.3,
        },
        ampEnv: { attack: 0.08, decay: 0.25, sustain: 0.7, release: 0.5 },
        lfo: {
          wave: "sine",
          rate: 4.5,
          pitchDepth: 12,
          filterDepth: 200,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.45,
          delayFeedback: 35,
          delayMix: 22,
          reverbMix: 45,
          distortionDrive: 0,
          chorusRate: 0.6,
          chorusDepth: 38,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 52,
      },
      {
        name: "Techno Stab",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 0, level: 80 },
        noiseLevel: 8,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 3000,
          resonance: 12,
          envAmount: 2200,
          attack: 0.001,
          decay: 0.12,
        },
        ampEnv: { attack: 0.001, decay: 0.15, sustain: 0.4, release: 0.2 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.25,
          delayFeedback: 40,
          delayMix: 20,
          reverbMix: 25,
          distortionDrive: 22,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 53,
      },
      {
        name: "Sync Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 24, level: 70 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 4500,
          resonance: 10,
          envAmount: 2800,
          attack: 0.04,
          decay: 0.22,
        },
        ampEnv: { attack: 0.01, decay: 0.18, sustain: 0.75, release: 0.35 },
        lfo: {
          wave: "triangle",
          rate: 8,
          pitchDepth: 40,
          filterDepth: 1000,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.35,
          delayFeedback: 48,
          delayMix: 30,
          reverbMix: 32,
          distortionDrive: 15,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 49,
      },
      {
        name: "Arpeggio Lead",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 12, level: 60 },
        noiseLevel: 5,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3800,
          resonance: 6,
          envAmount: 2000,
          attack: 0.001,
          decay: 0.1,
        },
        ampEnv: { attack: 0.001, decay: 0.12, sustain: 0.5, release: 0.18 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.333,
          delayFeedback: 50,
          delayMix: 40,
          reverbMix: 35,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 51,
      },
      {
        name: "Flanger Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 7, level: 80 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3200,
          resonance: 5,
          envAmount: 1600,
          attack: 0.05,
          decay: 0.28,
        },
        ampEnv: { attack: 0.02, decay: 0.2, sustain: 0.8, release: 0.38 },
        lfo: {
          wave: "sine",
          rate: 5.5,
          pitchDepth: 18,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.375,
          delayFeedback: 38,
          delayMix: 25,
          reverbMix: 32,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.8,
          flangerDepth: 65,
          flangerFeedbackAmount: 70,
        },
        masterVolume: 50,
      },
      {
        name: "Acid Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: -7, level: 70 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 1200,
          resonance: 20,
          envAmount: 4000,
          attack: 0.01,
          decay: 0.35,
        },
        ampEnv: { attack: 0.01, decay: 0.25, sustain: 0.6, release: 0.3 },
        lfo: {
          wave: "sine",
          rate: 9,
          pitchDepth: 0,
          filterDepth: 2000,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 42,
          delayMix: 22,
          reverbMix: 28,
          distortionDrive: 18,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 50,
      },
      {
        name: "Bright Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 7, level: 50 },
        noiseLevel: 10,
        octave: 6,
        filter: {
          type: "lowpass",
          cutoff: 6000,
          resonance: 3,
          envAmount: 2500,
          attack: 0.02,
          decay: 0.2,
        },
        ampEnv: { attack: 0.01, decay: 0.15, sustain: 0.7, release: 0.3 },
        lfo: {
          wave: "sine",
          rate: 6,
          pitchDepth: 20,
          filterDepth: 400,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 40,
          delayMix: 28,
          reverbMix: 38,
          distortionDrive: 5,
          chorusRate: 0.7,
          chorusDepth: 35,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Gritty Lead",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 10, level: 95 },
        noiseLevel: 12,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 2800,
          resonance: 14,
          envAmount: 2200,
          attack: 0.02,
          decay: 0.18,
        },
        ampEnv: { attack: 0.01, decay: 0.12, sustain: 0.85, release: 0.28 },
        lfo: {
          wave: "sine",
          rate: 6.5,
          pitchDepth: 22,
          filterDepth: 700,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 45,
          delayMix: 25,
          reverbMix: 25,
          distortionDrive: 42,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 46,
      },
      {
        name: "Chorus Lead",
        osc1: { wave: "sawtooth", detune: -5, level: 85 },
        osc2: { wave: "sawtooth", detune: 5, level: 85 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3200,
          resonance: 4,
          envAmount: 1500,
          attack: 0.05,
          decay: 0.25,
        },
        ampEnv: { attack: 0.02, decay: 0.2, sustain: 0.75, release: 0.4 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 15,
          filterDepth: 300,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.375,
          delayFeedback: 35,
          delayMix: 25,
          reverbMix: 35,
          distortionDrive: 0,
          chorusRate: 1.2,
          chorusDepth: 55,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 50,
      },
      {
        name: "Monophonic Lead",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 0, level: 60 },
        noiseLevel: 3,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 2800,
          resonance: 7,
          envAmount: 1800,
          attack: 0.04,
          decay: 0.22,
        },
        ampEnv: { attack: 0.02, decay: 0.18, sustain: 0.8, release: 0.32 },
        lfo: {
          wave: "sine",
          rate: 5.5,
          pitchDepth: 18,
          filterDepth: 500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.35,
          delayFeedback: 38,
          delayMix: 22,
          reverbMix: 30,
          distortionDrive: 10,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 51,
      },
      {
        name: "Detune Lead",
        osc1: { wave: "sawtooth", detune: -15, level: 90 },
        osc2: { wave: "sawtooth", detune: 15, level: 90 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 3600,
          resonance: 5,
          envAmount: 2000,
          attack: 0.05,
          decay: 0.28,
        },
        ampEnv: { attack: 0.02, decay: 0.2, sustain: 0.78, release: 0.4 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 20,
          filterDepth: 450,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 40,
          delayMix: 30,
          reverbMix: 38,
          distortionDrive: 0,
          chorusRate: 0.6,
          chorusDepth: 42,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 49,
      },
    ],
    pad: [
      {
        name: "Warm Pad",
        osc1: { wave: "sawtooth", detune: 0, level: 80 },
        osc2: { wave: "sawtooth", detune: 7, level: 80 },
        noiseLevel: 0,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 1500,
          resonance: 1,
          envAmount: 500,
          attack: 0.8,
          decay: 0.5,
        },
        ampEnv: { attack: 0.8, decay: 0.3, sustain: 0.7, release: 1.2 },
        lfo: {
          wave: "sine",
          rate: 0.5,
          pitchDepth: 8,
          filterDepth: 300,
          ampDepth: 10,
        },
        effects: {
          delayTime: 0.5,
          delayFeedback: 40,
          delayMix: 20,
          reverbMix: 60,
        },
        masterVolume: 40,
      },
      {
        name: "Strings Pad",
        osc1: { wave: "sawtooth", detune: -7, level: 70 },
        osc2: { wave: "sawtooth", detune: 7, level: 70 },
        noiseLevel: 2,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 2000,
          resonance: 2,
          envAmount: 800,
          attack: 1.0,
          decay: 0.8,
        },
        ampEnv: { attack: 1.0, decay: 0.5, sustain: 0.8, release: 1.5 },
        lfo: {
          wave: "sine",
          rate: 0.3,
          pitchDepth: 5,
          filterDepth: 200,
          ampDepth: 8,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 35,
          delayMix: 15,
          reverbMix: 70,
        },
        masterVolume: 45,
      },
      {
        name: "Choir Pad",
        osc1: { wave: "sine", detune: 0, level: 90 },
        osc2: { wave: "triangle", detune: 12, level: 60 },
        noiseLevel: 3,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 2500,
          resonance: 1.5,
          envAmount: 600,
          attack: 1.2,
          decay: 0.6,
        },
        ampEnv: { attack: 1.2, decay: 0.4, sustain: 0.75, release: 1.8 },
        lfo: {
          wave: "sine",
          rate: 0.4,
          pitchDepth: 12,
          filterDepth: 400,
          ampDepth: 12,
        },
        effects: {
          delayTime: 0.6,
          delayFeedback: 45,
          delayMix: 25,
          reverbMix: 75,
        },
        masterVolume: 40,
      },
      {
        name: "Dark Pad",
        osc1: { wave: "triangle", detune: 0, level: 100 },
        osc2: { wave: "sine", detune: -12, level: 70 },
        noiseLevel: 5,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 800,
          resonance: 3,
          envAmount: 200,
          attack: 1.5,
          decay: 1.0,
        },
        ampEnv: { attack: 1.5, decay: 0.6, sustain: 0.7, release: 2.0 },
        lfo: {
          wave: "triangle",
          rate: 0.2,
          pitchDepth: 3,
          filterDepth: 150,
          ampDepth: 15,
        },
        effects: {
          delayTime: 0.7,
          delayFeedback: 50,
          delayMix: 30,
          reverbMix: 80,
        },
        masterVolume: 45,
      },
      {
        name: "Shimmer Pad",
        osc1: { wave: "sine", detune: 0, level: 80 },
        osc2: { wave: "triangle", detune: 24, level: 60 },
        noiseLevel: 8,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 3000,
          resonance: 5,
          envAmount: 1000,
          attack: 0.9,
          decay: 0.7,
        },
        ampEnv: { attack: 0.9, decay: 0.5, sustain: 0.6, release: 1.5 },
        lfo: {
          wave: "sine",
          rate: 2,
          pitchDepth: 20,
          filterDepth: 800,
          ampDepth: 20,
        },
        effects: {
          delayTime: 0.5,
          delayFeedback: 60,
          delayMix: 40,
          reverbMix: 85,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 40,
      },
      {
        name: "Lush Pad",
        osc1: { wave: "sawtooth", detune: -10, level: 75 },
        osc2: { wave: "sawtooth", detune: 10, level: 75 },
        noiseLevel: 3,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 1800,
          resonance: 2,
          envAmount: 600,
          attack: 0.9,
          decay: 0.6,
        },
        ampEnv: { attack: 0.9, decay: 0.4, sustain: 0.75, release: 1.4 },
        lfo: {
          wave: "sine",
          rate: 0.6,
          pitchDepth: 10,
          filterDepth: 350,
          ampDepth: 12,
        },
        effects: {
          delayTime: 0.55,
          delayFeedback: 42,
          delayMix: 22,
          reverbMix: 68,
          distortionDrive: 0,
          chorusRate: 0.4,
          chorusDepth: 50,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 42,
      },
      {
        name: "Ambient Pad",
        osc1: { wave: "sine", detune: 0, level: 85 },
        osc2: { wave: "triangle", detune: 19, level: 70 },
        noiseLevel: 10,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 2200,
          resonance: 1.8,
          envAmount: 700,
          attack: 1.3,
          decay: 0.8,
        },
        ampEnv: { attack: 1.3, decay: 0.5, sustain: 0.72, release: 1.9 },
        lfo: {
          wave: "sine",
          rate: 0.35,
          pitchDepth: 8,
          filterDepth: 300,
          ampDepth: 15,
        },
        effects: {
          delayTime: 0.65,
          delayFeedback: 48,
          delayMix: 32,
          reverbMix: 78,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 41,
      },
      {
        name: "Analog Pad",
        osc1: { wave: "sawtooth", detune: 0, level: 80 },
        osc2: { wave: "square", detune: 5, level: 70 },
        noiseLevel: 6,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 1600,
          resonance: 2.5,
          envAmount: 550,
          attack: 0.85,
          decay: 0.55,
        },
        ampEnv: { attack: 0.85, decay: 0.35, sustain: 0.75, release: 1.3 },
        lfo: {
          wave: "triangle",
          rate: 0.45,
          pitchDepth: 6,
          filterDepth: 250,
          ampDepth: 10,
        },
        effects: {
          delayTime: 0.48,
          delayFeedback: 38,
          delayMix: 18,
          reverbMix: 62,
          distortionDrive: 8,
          chorusRate: 0.6,
          chorusDepth: 30,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 43,
      },
      {
        name: "Evolving Pad",
        osc1: { wave: "sawtooth", detune: -8, level: 75 },
        osc2: { wave: "triangle", detune: 8, level: 75 },
        noiseLevel: 5,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 1900,
          resonance: 3,
          envAmount: 900,
          attack: 1.1,
          decay: 0.9,
        },
        ampEnv: { attack: 1.1, decay: 0.6, sustain: 0.7, release: 1.7 },
        lfo: {
          wave: "sine",
          rate: 0.25,
          pitchDepth: 12,
          filterDepth: 600,
          ampDepth: 18,
        },
        effects: {
          delayTime: 0.6,
          delayFeedback: 50,
          delayMix: 28,
          reverbMix: 72,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.2,
          flangerDepth: 35,
          flangerFeedbackAmount: 60,
        },
        masterVolume: 41,
      },
      {
        name: "Crystal Pad",
        osc1: { wave: "sine", detune: 0, level: 90 },
        osc2: { wave: "triangle", detune: 12, level: 65 },
        noiseLevel: 12,
        octave: 5,
        filter: {
          type: "highpass",
          cutoff: 400,
          resonance: 4,
          envAmount: 800,
          attack: 1.0,
          decay: 0.7,
        },
        ampEnv: { attack: 1.0, decay: 0.45, sustain: 0.68, release: 1.6 },
        lfo: {
          wave: "sine",
          rate: 1.5,
          pitchDepth: 18,
          filterDepth: 600,
          ampDepth: 22,
        },
        effects: {
          delayTime: 0.52,
          delayFeedback: 55,
          delayMix: 38,
          reverbMix: 82,
          distortionDrive: 0,
          chorusRate: 0.8,
          chorusDepth: 45,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 39,
      },
      {
        name: "Sweep Pad",
        osc1: { wave: "sawtooth", detune: 0, level: 85 },
        osc2: { wave: "square", detune: 7, level: 75 },
        noiseLevel: 4,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 1200,
          resonance: 6,
          envAmount: 1500,
          attack: 1.4,
          decay: 1.2,
        },
        ampEnv: { attack: 1.0, decay: 0.5, sustain: 0.73, release: 1.5 },
        lfo: {
          wave: "triangle",
          rate: 0.3,
          pitchDepth: 5,
          filterDepth: 800,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.58,
          delayFeedback: 45,
          delayMix: 25,
          reverbMix: 70,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 42,
      },
      {
        name: "Dream Pad",
        osc1: { wave: "sine", detune: 0, level: 80 },
        osc2: { wave: "sine", detune: 7, level: 80 },
        noiseLevel: 8,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 2800,
          resonance: 2,
          envAmount: 650,
          attack: 1.2,
          decay: 0.7,
        },
        ampEnv: { attack: 1.2, decay: 0.5, sustain: 0.7, release: 1.8 },
        lfo: {
          wave: "sine",
          rate: 0.5,
          pitchDepth: 15,
          filterDepth: 400,
          ampDepth: 15,
        },
        effects: {
          delayTime: 0.62,
          delayFeedback: 52,
          delayMix: 35,
          reverbMix: 80,
          distortionDrive: 0,
          chorusRate: 0.7,
          chorusDepth: 50,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 40,
      },
      {
        name: "Ethereal Pad",
        osc1: { wave: "triangle", detune: 0, level: 85 },
        osc2: { wave: "sine", detune: 24, level: 70 },
        noiseLevel: 15,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 2500,
          resonance: 6,
          envAmount: 1100,
          attack: 1.0,
          decay: 0.8,
        },
        ampEnv: { attack: 1.0, decay: 0.55, sustain: 0.65, release: 1.7 },
        lfo: {
          wave: "sine",
          rate: 1.8,
          pitchDepth: 22,
          filterDepth: 900,
          ampDepth: 25,
        },
        effects: {
          delayTime: 0.55,
          delayFeedback: 58,
          delayMix: 42,
          reverbMix: 88,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.5,
          flangerDepth: 48,
          flangerFeedbackAmount: 65,
        },
        masterVolume: 38,
      },
      {
        name: "Soft Pad",
        osc1: { wave: "triangle", detune: 0, level: 90 },
        osc2: { wave: "sine", detune: 12, level: 75 },
        noiseLevel: 2,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 1700,
          resonance: 1.5,
          envAmount: 450,
          attack: 0.95,
          decay: 0.5,
        },
        ampEnv: { attack: 0.95, decay: 0.35, sustain: 0.78, release: 1.4 },
        lfo: {
          wave: "sine",
          rate: 0.4,
          pitchDepth: 6,
          filterDepth: 200,
          ampDepth: 8,
        },
        effects: {
          delayTime: 0.5,
          delayFeedback: 40,
          delayMix: 20,
          reverbMix: 65,
          distortionDrive: 0,
          chorusRate: 0.6,
          chorusDepth: 35,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 43,
      },
      {
        name: "Digital Pad",
        osc1: { wave: "square", detune: 0, level: 80 },
        osc2: { wave: "triangle", detune: 19, level: 70 },
        noiseLevel: 8,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 2400,
          resonance: 4,
          envAmount: 850,
          attack: 0.88,
          decay: 0.65,
        },
        ampEnv: { attack: 0.88, decay: 0.4, sustain: 0.72, release: 1.35 },
        lfo: {
          wave: "square",
          rate: 0.8,
          pitchDepth: 10,
          filterDepth: 500,
          ampDepth: 20,
        },
        effects: {
          delayTime: 0.48,
          delayFeedback: 44,
          delayMix: 26,
          reverbMix: 68,
          distortionDrive: 5,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 42,
      },
      {
        name: "Glass Pad",
        osc1: { wave: "sine", detune: 0, level: 85 },
        osc2: { wave: "triangle", detune: 31, level: 60 },
        noiseLevel: 18,
        octave: 6,
        filter: {
          type: "highpass",
          cutoff: 600,
          resonance: 5,
          envAmount: 900,
          attack: 0.92,
          decay: 0.68,
        },
        ampEnv: { attack: 0.92, decay: 0.48, sustain: 0.62, release: 1.55 },
        lfo: {
          wave: "sine",
          rate: 2.2,
          pitchDepth: 25,
          filterDepth: 700,
          ampDepth: 28,
        },
        effects: {
          delayTime: 0.5,
          delayFeedback: 62,
          delayMix: 45,
          reverbMix: 85,
          distortionDrive: 0,
          chorusRate: 0.9,
          chorusDepth: 52,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 38,
      },
      {
        name: "Texture Pad",
        osc1: { wave: "sawtooth", detune: -12, level: 75 },
        osc2: { wave: "square", detune: 12, level: 75 },
        noiseLevel: 10,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 1400,
          resonance: 3.5,
          envAmount: 600,
          attack: 1.2,
          decay: 0.9,
        },
        ampEnv: { attack: 1.2, decay: 0.55, sustain: 0.7, release: 1.8 },
        lfo: {
          wave: "triangle",
          rate: 0.35,
          pitchDepth: 8,
          filterDepth: 400,
          ampDepth: 18,
        },
        effects: {
          delayTime: 0.68,
          delayFeedback: 48,
          delayMix: 28,
          reverbMix: 75,
          distortionDrive: 12,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 42,
      },
      {
        name: "Metallic Pad",
        osc1: { wave: "square", detune: 0, level: 80 },
        osc2: { wave: "triangle", detune: 24, level: 70 },
        noiseLevel: 12,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 2800,
          resonance: 8,
          envAmount: 1200,
          attack: 0.95,
          decay: 0.75,
        },
        ampEnv: { attack: 0.95, decay: 0.5, sustain: 0.68, release: 1.6 },
        lfo: {
          wave: "sine",
          rate: 1.2,
          pitchDepth: 16,
          filterDepth: 700,
          ampDepth: 22,
        },
        effects: {
          delayTime: 0.52,
          delayFeedback: 54,
          delayMix: 35,
          reverbMix: 78,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.6,
          flangerDepth: 58,
          flangerFeedbackAmount: 75,
        },
        masterVolume: 40,
      },
      {
        name: "Space Pad",
        osc1: { wave: "sine", detune: 0, level: 88 },
        osc2: { wave: "triangle", detune: 19, level: 72 },
        noiseLevel: 20,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 2600,
          resonance: 2.5,
          envAmount: 750,
          attack: 1.4,
          decay: 0.95,
        },
        ampEnv: { attack: 1.4, decay: 0.6, sustain: 0.72, release: 2.0 },
        lfo: {
          wave: "sine",
          rate: 0.28,
          pitchDepth: 10,
          filterDepth: 500,
          ampDepth: 20,
        },
        effects: {
          delayTime: 0.72,
          delayFeedback: 56,
          delayMix: 38,
          reverbMix: 90,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.25,
          flangerDepth: 42,
          flangerFeedbackAmount: 55,
        },
        masterVolume: 39,
      },
    ],
    fx: [
      {
        name: "Laser Zap",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 7, level: 80 },
        noiseLevel: 15,
        octave: 6,
        filter: {
          type: "bandpass",
          cutoff: 5000,
          resonance: 20,
          envAmount: -4000,
          attack: 0.001,
          decay: 0.3,
        },
        ampEnv: { attack: 0.001, decay: 0.4, sustain: 0.2, release: 0.3 },
        lfo: {
          wave: "sawtooth",
          rate: 15,
          pitchDepth: 100,
          filterDepth: 3000,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.15,
          delayFeedback: 60,
          delayMix: 40,
          reverbMix: 50,
        },
        masterVolume: 50,
      },
      {
        name: "Space Sweep",
        osc1: { wave: "sine", detune: 0, level: 90 },
        osc2: { wave: "triangle", detune: 19, level: 70 },
        noiseLevel: 20,
        octave: 5,
        filter: {
          type: "highpass",
          cutoff: 200,
          resonance: 8,
          envAmount: 3000,
          attack: 2.0,
          decay: 1.5,
        },
        ampEnv: { attack: 0.5, decay: 1.0, sustain: 0.5, release: 2.0 },
        lfo: {
          wave: "sine",
          rate: 0.3,
          pitchDepth: 50,
          filterDepth: 2000,
          ampDepth: 30,
        },
        effects: {
          delayTime: 0.8,
          delayFeedback: 70,
          delayMix: 60,
          reverbMix: 90,
        },
        masterVolume: 45,
      },
      {
        name: "Robot Voice",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "square", detune: -24, level: 100 },
        noiseLevel: 25,
        octave: 4,
        filter: {
          type: "bandpass",
          cutoff: 1500,
          resonance: 15,
          envAmount: 0,
          attack: 0.01,
          decay: 0.1,
        },
        ampEnv: { attack: 0.01, decay: 0.1, sustain: 0.8, release: 0.2 },
        lfo: {
          wave: "square",
          rate: 8,
          pitchDepth: 0,
          filterDepth: 1000,
          ampDepth: 50,
        },
        effects: {
          delayTime: 0.2,
          delayFeedback: 50,
          delayMix: 30,
          reverbMix: 40,
        },
        masterVolume: 50,
      },
      {
        name: "Wind Noise",
        osc1: { wave: "sine", detune: 0, level: 30 },
        osc2: { wave: "triangle", detune: 12, level: 30 },
        noiseLevel: 100,
        octave: 3,
        filter: {
          type: "bandpass",
          cutoff: 2000,
          resonance: 5,
          envAmount: 0,
          attack: 0.5,
          decay: 0.5,
        },
        ampEnv: { attack: 2.0, decay: 1.0, sustain: 0.7, release: 2.5 },
        lfo: {
          wave: "sine",
          rate: 0.5,
          pitchDepth: 0,
          filterDepth: 1500,
          ampDepth: 40,
        },
        effects: {
          delayTime: 0.6,
          delayFeedback: 60,
          delayMix: 40,
          reverbMix: 85,
        },
        masterVolume: 45,
      },
      {
        name: "Glitch Hit",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 31, level: 100 },
        noiseLevel: 40,
        octave: 5,
        filter: {
          type: "notch",
          cutoff: 3000,
          resonance: 25,
          envAmount: -2000,
          attack: 0.001,
          decay: 0.05,
        },
        ampEnv: { attack: 0.001, decay: 0.08, sustain: 0.1, release: 0.15 },
        lfo: {
          wave: "square",
          rate: 20,
          pitchDepth: 200,
          filterDepth: 4000,
          ampDepth: 80,
        },
        effects: {
          delayTime: 0.1,
          delayFeedback: 80,
          delayMix: 50,
          reverbMix: 60,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 50,
      },
      {
        name: "Sci-Fi Riser",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 12, level: 80 },
        noiseLevel: 25,
        octave: 4,
        filter: {
          type: "lowpass",
          cutoff: 800,
          resonance: 10,
          envAmount: 4500,
          attack: 2.5,
          decay: 0.5,
        },
        ampEnv: { attack: 2.0, decay: 0.5, sustain: 0.8, release: 1.5 },
        lfo: {
          wave: "sine",
          rate: 0.2,
          pitchDepth: 80,
          filterDepth: 2500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 65,
          delayMix: 45,
          reverbMix: 70,
          distortionDrive: 15,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 47,
      },
      {
        name: "Impact Hit",
        osc1: { wave: "sine", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: -12, level: 80 },
        noiseLevel: 60,
        octave: 2,
        filter: {
          type: "lowpass",
          cutoff: 150,
          resonance: 8,
          envAmount: 1000,
          attack: 0.001,
          decay: 0.15,
        },
        ampEnv: { attack: 0.001, decay: 0.2, sustain: 0.3, release: 0.5 },
        lfo: {
          wave: "sine",
          rate: 5,
          pitchDepth: 0,
          filterDepth: 0,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 40,
          delayMix: 25,
          reverbMix: 60,
          distortionDrive: 35,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 60,
      },
      {
        name: "Sweep Down",
        osc1: { wave: "sawtooth", detune: 0, level: 100 },
        osc2: { wave: "triangle", detune: 7, level: 70 },
        noiseLevel: 15,
        octave: 5,
        filter: {
          type: "lowpass",
          cutoff: 8000,
          resonance: 12,
          envAmount: -6000,
          attack: 0.01,
          decay: 1.5,
        },
        ampEnv: { attack: 0.01, decay: 1.2, sustain: 0.4, release: 0.8 },
        lfo: {
          wave: "sine",
          rate: 0.5,
          pitchDepth: -40,
          filterDepth: -1500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.35,
          delayFeedback: 55,
          delayMix: 35,
          reverbMix: 65,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Alarm Siren",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 12, level: 80 },
        noiseLevel: 0,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 2000,
          resonance: 15,
          envAmount: 0,
          attack: 0.01,
          decay: 0.1,
        },
        ampEnv: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.2 },
        lfo: {
          wave: "triangle",
          rate: 4,
          pitchDepth: 200,
          filterDepth: 1500,
          ampDepth: 0,
        },
        effects: {
          delayTime: 0.25,
          delayFeedback: 50,
          delayMix: 30,
          reverbMix: 40,
          distortionDrive: 20,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 52,
      },
      {
        name: "Radio Static",
        osc1: { wave: "square", detune: 0, level: 40 },
        osc2: { wave: "sawtooth", detune: 24, level: 40 },
        noiseLevel: 90,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 3500,
          resonance: 12,
          envAmount: 0,
          attack: 0.1,
          decay: 0.2,
        },
        ampEnv: { attack: 0.1, decay: 0.3, sustain: 0.85, release: 0.4 },
        lfo: {
          wave: "square",
          rate: 10,
          pitchDepth: 0,
          filterDepth: 2000,
          ampDepth: 60,
        },
        effects: {
          delayTime: 0.15,
          delayFeedback: 45,
          delayMix: 25,
          reverbMix: 35,
          distortionDrive: 30,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Underwater",
        osc1: { wave: "sine", detune: 0, level: 85 },
        osc2: { wave: "triangle", detune: 5, level: 75 },
        noiseLevel: 30,
        octave: 3,
        filter: {
          type: "lowpass",
          cutoff: 600,
          resonance: 6,
          envAmount: 400,
          attack: 1.0,
          decay: 0.8,
        },
        ampEnv: { attack: 0.5, decay: 0.8, sustain: 0.7, release: 1.5 },
        lfo: {
          wave: "sine",
          rate: 0.4,
          pitchDepth: 15,
          filterDepth: 300,
          ampDepth: 25,
        },
        effects: {
          delayTime: 0.55,
          delayFeedback: 60,
          delayMix: 50,
          reverbMix: 85,
          distortionDrive: 0,
          chorusRate: 0.3,
          chorusDepth: 45,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 45,
      },
      {
        name: "Transmission",
        osc1: { wave: "square", detune: 0, level: 80 },
        osc2: { wave: "sawtooth", detune: 19, level: 70 },
        noiseLevel: 45,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 2800,
          resonance: 18,
          envAmount: 0,
          attack: 0.05,
          decay: 0.1,
        },
        ampEnv: { attack: 0.05, decay: 0.15, sustain: 0.7, release: 0.3 },
        lfo: {
          wave: "square",
          rate: 12,
          pitchDepth: 50,
          filterDepth: 1800,
          ampDepth: 70,
        },
        effects: {
          delayTime: 0.18,
          delayFeedback: 55,
          delayMix: 35,
          reverbMix: 45,
          distortionDrive: 38,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Thunderstorm",
        osc1: { wave: "sine", detune: 0, level: 70 },
        osc2: { wave: "triangle", detune: -12, level: 60 },
        noiseLevel: 80,
        octave: 2,
        filter: {
          type: "lowpass",
          cutoff: 500,
          resonance: 4,
          envAmount: 300,
          attack: 0.8,
          decay: 1.2,
        },
        ampEnv: { attack: 0.3, decay: 1.5, sustain: 0.6, release: 2.0 },
        lfo: {
          wave: "sine",
          rate: 0.2,
          pitchDepth: 10,
          filterDepth: 200,
          ampDepth: 35,
        },
        effects: {
          delayTime: 0.65,
          delayFeedback: 65,
          delayMix: 45,
          reverbMix: 88,
          distortionDrive: 10,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 46,
      },
      {
        name: "Digital Glitch",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "sawtooth", detune: 36, level: 90 },
        noiseLevel: 50,
        octave: 6,
        filter: {
          type: "notch",
          cutoff: 4000,
          resonance: 20,
          envAmount: -3000,
          attack: 0.001,
          decay: 0.04,
        },
        ampEnv: { attack: 0.001, decay: 0.05, sustain: 0.15, release: 0.1 },
        lfo: {
          wave: "square",
          rate: 25,
          pitchDepth: 300,
          filterDepth: 5000,
          ampDepth: 90,
        },
        effects: {
          delayTime: 0.08,
          delayFeedback: 75,
          delayMix: 55,
          reverbMix: 55,
          distortionDrive: 45,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 48,
      },
      {
        name: "Helicopter",
        osc1: { wave: "sawtooth", detune: 0, level: 70 },
        osc2: { wave: "square", detune: -5, level: 60 },
        noiseLevel: 70,
        octave: 2,
        filter: {
          type: "bandpass",
          cutoff: 800,
          resonance: 8,
          envAmount: 0,
          attack: 0.1,
          decay: 0.2,
        },
        ampEnv: { attack: 0.1, decay: 0.2, sustain: 0.9, release: 0.5 },
        lfo: {
          wave: "square",
          rate: 8,
          pitchDepth: 0,
          filterDepth: 600,
          ampDepth: 50,
        },
        effects: {
          delayTime: 0.22,
          delayFeedback: 60,
          delayMix: 35,
          reverbMix: 50,
          distortionDrive: 25,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 1.2,
          flangerDepth: 55,
          flangerFeedbackAmount: 70,
        },
        masterVolume: 50,
      },
      {
        name: "Cosmic Ray",
        osc1: { wave: "sine", detune: 0, level: 90 },
        osc2: { wave: "triangle", detune: 31, level: 75 },
        noiseLevel: 35,
        octave: 6,
        filter: {
          type: "highpass",
          cutoff: 1000,
          resonance: 15,
          envAmount: 3500,
          attack: 0.02,
          decay: 0.8,
        },
        ampEnv: { attack: 0.02, decay: 0.9, sustain: 0.3, release: 1.2 },
        lfo: {
          wave: "sawtooth",
          rate: 12,
          pitchDepth: 150,
          filterDepth: 2500,
          ampDepth: 40,
        },
        effects: {
          delayTime: 0.3,
          delayFeedback: 70,
          delayMix: 55,
          reverbMix: 80,
          distortionDrive: 0,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.8,
          flangerDepth: 65,
          flangerFeedbackAmount: 75,
        },
        masterVolume: 46,
      },
      {
        name: "Steam Vent",
        osc1: { wave: "triangle", detune: 0, level: 50 },
        osc2: { wave: "sine", detune: 7, level: 40 },
        noiseLevel: 95,
        octave: 4,
        filter: {
          type: "highpass",
          cutoff: 2000,
          resonance: 6,
          envAmount: 1500,
          attack: 0.3,
          decay: 0.6,
        },
        ampEnv: { attack: 0.3, decay: 0.8, sustain: 0.75, release: 1.0 },
        lfo: {
          wave: "sine",
          rate: 0.6,
          pitchDepth: 0,
          filterDepth: 800,
          ampDepth: 30,
        },
        effects: {
          delayTime: 0.4,
          delayFeedback: 50,
          delayMix: 30,
          reverbMix: 70,
          distortionDrive: 15,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 47,
      },
      {
        name: "Alien Voice",
        osc1: { wave: "square", detune: 0, level: 90 },
        osc2: { wave: "sawtooth", detune: -19, level: 85 },
        noiseLevel: 30,
        octave: 4,
        filter: {
          type: "bandpass",
          cutoff: 1200,
          resonance: 18,
          envAmount: 2000,
          attack: 0.08,
          decay: 0.3,
        },
        ampEnv: { attack: 0.05, decay: 0.25, sustain: 0.65, release: 0.4 },
        lfo: {
          wave: "triangle",
          rate: 6,
          pitchDepth: 80,
          filterDepth: 1500,
          ampDepth: 40,
        },
        effects: {
          delayTime: 0.28,
          delayFeedback: 58,
          delayMix: 40,
          reverbMix: 55,
          distortionDrive: 22,
          chorusRate: 0.9,
          chorusDepth: 48,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 49,
      },
      {
        name: "Electric Buzz",
        osc1: { wave: "square", detune: 0, level: 100 },
        osc2: { wave: "square", detune: 1, level: 95 },
        noiseLevel: 20,
        octave: 5,
        filter: {
          type: "bandpass",
          cutoff: 3000,
          resonance: 22,
          envAmount: 0,
          attack: 0.01,
          decay: 0.05,
        },
        ampEnv: { attack: 0.01, decay: 0.05, sustain: 0.95, release: 0.15 },
        lfo: {
          wave: "square",
          rate: 18,
          pitchDepth: 10,
          filterDepth: 2000,
          ampDepth: 75,
        },
        effects: {
          delayTime: 0.12,
          delayFeedback: 65,
          delayMix: 35,
          reverbMix: 40,
          distortionDrive: 40,
          chorusRate: 0.5,
          chorusDepth: 0,
          flangerRate: 0.3,
          flangerDepth: 0,
          flangerFeedbackAmount: 50,
        },
        masterVolume: 50,
      },
    ],
  };
}
